python3 PM_Poshan.py pm_poshan pm-poshan_access-across-india.csv
python3 PM_Poshan_onboard.py pm_poshan pm-poshan_state-onboarded.csv
python3 PGI_started.py pgi pgi_program-started.cs
python3 PGI_all_dashboard.py pgi pgi_all-dashboard.csv
python3 PGI_performance.py pgi pgi_state-wise-performance.csv
python3 UDISE_all_dashboard.py udise udise-all-dashboard.csv
python3 UDISE_program_started.py udise udise_program-started.csv
python3 NAS_all_dashboard.py nas nas_all-dashboard.csv
python3 NAS_program_started.py nas nas_program-started.csv
python3 NISHTHA_consumption.py nishtha diksha_nishtha_consumption-by-district.csv
python3 NISHTHA_consumption_by_courses.py nishtha diksha_nishtha_consumption-by-course.csv
python3 NISHTHA_percentage_enrollment_certification.py nishtha diksha_nishtha_percentage-enrollment-certification.csv
python3 NISHTHA_program_started.py nishtha diksha_nishtha_program-started.csv
python3 NISHTHA_tot_courses_medium.py nishtha diksha_nishtha_tot-courses-medium.csv
python3 DIKSHA_etb_coverage.py diksha diksha_etb_coverage-status.csv
python3 DIKSHA_etb_learning_session.py diksha diksha_etb_learning-session.csv
python3 DIKSHA_etb_plays_per_capita.py diksha diksha_etb_plays-per-capita.csv
python3 DIKSHA_etb_qr_coverage.py diksha diksha_etb_qr-coverage.csv
python3 DIKSHA_etb_program_started.py diksha diksha_etb_program-started.csv
python3 DIKSHA_etb_etb_coverage.py diksha diksha_etb_etb-coverage.csv
python3 MICRO_Improvement.py micro_improvement micro-improvement_district.csv
python3 MICRO_Improvement_all_dashboard.py micro_improvement micro-improvement_all-dashboard.csv
python3 NCERT_program_started.py ncert diksha_quiz_program-started.csv
python3 NCERT_quiz_participation.py ncert diksha_quiz_state-participation.csv
python3 NCERT_quiz_started_plan.py ncert diksha_quiz-started-plan.csv
python3 NCF_all_dashboard.py ncf ncf_all-dashboard.csv
python3 NCF_language.py ncf language_wise_count.csv
python3 NCF_state_wise.py ncf state_wise_count.csv
python3 NIPUN_Barath_textbook.py nipun_barath nipunbharat_lo-covered-by-textbook.csv