python3 DIKSHA_etb_coverage.py diksha vsk_diksha_etb_coverage-status.csv
python3 DIKSHA_learning_session.py diksha diksha_etb_learning-session.csv
python3 DIKSHA_etb_plays_per_capita.py diksha diksha_etb_plays-per-capita.csv
python3 DIKSHA_etb_qr_coverage.py diksha vsk_diksha_etb_qr-coverage.csv

python3 NISHTHA_course_wise_status.py nishtha NISHTHA_course-wise_certification.csv
python3 NISHTHA_medium_instruction.py nishtha NISHTHA_medium_of_instructions.csv
python3 NISHTHA_district_wise_status.py nishtha NISHTHA_Program-wise_achieved_certificates.csv
python3 NISHTHA_implementation_status.py nishtha NISHTHA_program_implementation_status.csv
python3 NISHTHA_percentage_against_potential_base.py nishtha NISHTHA_Program-wise_achieved_certificates.csv

python3 NAS_state_wise_performance.py nas nas_all-dashboard.csv
python3 NAS_implementation_status.py nas nas_program-started.csv

python3 PGI_district_wise_performance.py pgi pgi_all-dashboard.csv
python3 PGI_state_wise_performance.py pgi pgi_state-wise-performance.csv

python3 PM_Poshan_progress_status.py pm-poshan pm-poshan_access-across-india.csv

python3 UDISE_state_wise_performance.py udise udise-all-dashboard.csv
python3 UDISE_implementation_status.py udise udise_program-started.csv
